### ISSUE TITLE
Application Controller should inherit from host

### ISSUE THREAD

**Issue by lewispb** [DEFRA/flood-risk-engine#200]
Currently the engine ApplicationController inherits from `ActionController::Base` and then the host Application Controller inherits from `FloodRiskEngine::ApplicationController`:

`ActionController::Base` -> `FloodRiskEngine::ApplicationController` -> `ApplicationController` (front-end)

However when pages are rendered by `FloodRiskEngine::ApplicationController` they have no knowledge of the host (front-end) ApplicationController. Therefore view helpers are not available.

I propose we switch this to the following:

`ActionController::Base` -> `ApplicationController` -> `FloodRiskEngine::ApplicationController`

See this for more info: https://www.amberbit.com/blog/2015/10/15/rails-mountable-engines/ but essentially we do this:

```
module FloodRiskEngine
  class ApplicationController < ::ApplicationController
  end
end
```

This currently breaks a few things such as path helpers used in the engine views but I think it's the right way to go. Interested on your thoughts.

**Comment by woodpigeon** [comment]
Interesting idea, though have some reservations about how it breaks isolation a bit. Could discuss this at some point
